# Generated by Django 5.2.10 on 2026-01-29 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VFDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(help_text='e.g. AC310, AC10', max_length=100)),
                ('power_rating', models.CharField(help_text='e.g. 0.75kW - 75kW', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='manuals/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vfd_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuals', to='hub.vfdmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('tags', models.CharField(help_text='Comma-separated tags e.g. installation, wiring', max_length=200)),
                ('related_vfd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='hub.vfdmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. E-01', max_length=50)),
                ('name', models.CharField(help_text='e.g. Overcurrent', max_length=200)),
                ('description', models.TextField()),
                ('troubleshooting_steps', models.TextField()),
                ('firmware_version', models.CharField(blank=True, help_text='Related Firmware Version', max_length=50)),
                ('vfd_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_codes', to='hub.vfdmodel')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
