# Generated by Django 5.2.10 on 2026-02-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_faq_category_manual_content_text_manual_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
